name: ADF Selective Deployment 
on: workflow_dispatch
jobs:
  Install-and-Import-PowerShell-Module:
    env:
      RESOURCE_GROUP_NAME: rg-adf-selective-deployment-test
      DATA_FACTORY_NAME: adf-selective-deployment-prod-njl
      LOCATION: EastUS
      ROOT_FOLDER: $GITHUB_ACTION_PATH
    runs-on:
      ubuntu-latest
    steps:
    - name: Checkout-Code-Repo
      uses: actions/checkout@v2
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          Install-Module Az.DataFactory -MinimumVersion "1.10.0" -Force
          Install-Module -Name "azure.datafactory.tools" -Force
          Import-Module -Name "azure.datafactory.tools" -Force
          Publish-AdfV2FromJson -RootFolder "${{ env.ROOT_FOLDER }}" -ResourceGroupName "${{ env.RESOURCE_GROUP_NAME }}" -DataFactoryName "${{ env.DATA_FACTORY_NAME }}" -Location "${{ env.LOCATION }}"
        azPSVersion: "latest"
#        FailOnStandardError: true
#        azurePowerShellVersion: LatestVersion```
