name: ADF Full Template Spec
on: workflow_dispatch
jobs:
  Run-Deployment-of-ADF-to-PROD:
    env:
      RESOURCE_GROUP_NAME: rg-adf-selective-deployment-test
      DATA_FACTORY_NAME: adf-selective-deployment-prod-njl2234666
      LOCATION: EastUS
    runs-on:
      ubuntu-latest
    steps:
    - name: Checkout Code Repo
      uses: actions/checkout@v2
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          Install-Module Az.DataFactory -MinimumVersion "1.10.0" -Force
          Install-Module -Name "azure.datafactory.tools" -Force
          Import-Module -Name "azure.datafactory.tools" -Force
          Publish-AdfV2FromJson -RootFolder "${{ github.workspace }}" -ResourceGroupName "${{ env.RESOURCE_GROUP_NAME }}" -DataFactoryName "${{ env.DATA_FACTORY_NAME }}" -Location "${{ env.LOCATION }}"
        azPSVersion: "latest"
    - name: Get ARM Template
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          $RootFolder = "${{ github.workspace }}"
          $AdfUtilitiesVersion = '0.1.6'
          Set-Location $RootFolder
          $packageJson = "{""scripts"": {""build"": ""node node_modules/@microsoft/azure-data-factory-utilities/lib/index""},""dependencies"": {""@microsoft/azure-data-factory-utilities"": ""^$AdfUtilitiesVersion""}}"
          Set-Content -Path "$RootFolder\package.json" -Value $packageJson -Force
          npm i @microsoft/azure-data-factory-utilities@latest
          $AdfName = Split-Path -Path $RootFolder -Leaf
          $adfAzurePath = "/subscriptions/126c93ce-f0a6-493c-8991-cdcbd797366d/resourceGroups/${{ env.RESOURCE_GROUP_NAME }}/providers/Microsoft.DataFactory/factories/adf-selective-deployment-prod-njl2234666"
          npm run build export $RootFolder $adfAzurePath "ArmTemplate"
          az ts create --name "spectest222" --resource-group "${{ env.RESOURCE_GROUP_NAME }}" --location "EastUS" --template-file "./ArmTemplate/ARMTemplateForFactory.json" --version "0.1"
        azPSVersion: "latest"
          
          # az deployment group export --name "$templateName" --resource-group "${{ env.RESOURCE_GROUP_NAME }}"  > output3.json
          # az ts create --name "testADFSPEC222" --version "1.0" --resource-group "${{ env.RESOURCE_GROUP_NAME }}" --location "${{ env.LOCATION }}" --template-file "./output3.json"
        # $templateName = az deployment group list --resource-group "${{ env.RESOURCE_GROUP_NAME }}" --query "[?properties.parameters.factoryName.value == 'adf-selective-deployment-prod-njl2234'] | [].name| [0]"

